data:
  source: openml
  dataset_id: 42585
  raw_data_path: "data/raw/penguins.csv"
  train_data_path: "data/processed/train.csv"
  test_data_path: "data/processed/test.csv"
  preprocessed_data_path: "data/processed/penguins_processed.csv"
  target_mapping: {"Adelie": 0, "Chinstrap": 1, "Gentoo": 2}

preprocessing:
  encoder_path: "models/encoder.pkl"
  categorical_cols: ["island", "sex"]
  target_col: "species"

model:
  type: RandomForestClassifier
  rf_model_path: "models/model.pkl"
  experiment_name: "palmer_penguins"
  train_params:
    n_estimators: ["n_estimators", 50, 300, 50]
    max_depth: ["max_depth", 3, 15]
    min_samples_split: ["min_samples_split", 2, 10]
    min_samples_leaf: ["min_samples_leaf", 1, 4]
    random_state: 42
    n_trials: 30

tests:
  metrics_path: "metrics/metrics.json"